default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: my_food_development

test:
  <<: *default
  database: my_food_test

production:
  <<: *default
  database: my_food_production
