# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f168a5c0bc91fbf62faf47910a42b6a4f93a40d4dc9408e1573067f7a5b72029c0c47ab02b4d9b2dcad1c838f36302c8587ef7d08b211a8e751488c8b52d28e

test:
  secret_key_base: 17040c7afa1ba65c7915042c05f236b7d5995c284e0ac66e699faadb2b1b50491605661569d7b82f066308025db402ae784462c357036000724a47d084f9e3f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
